# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://shidongwa.github.io/
date_format: "ordinal"
title: 老实说
# subtitle: ""
description: "石头记"
keywords: Stone, shidongwa, shidonghua, 石东华
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shi Donghua
organization: shidongwa.github.com
organization_url: https://shidongwa.github.com
github_username: shidongwa
location: Shanghai, China
email: 10189795@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
     href: /archives/
     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: shidongwa/shidongwa.github

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: shidongwa
    repo: blog-comments
    oauth:
        client_id: f91653438a450b7759bc
        client_secret: b46c6894e64e3e086debead5c9757d98dfbf765b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: shidongwa
    repo: blog-comments
    clientID: f91653438a450b7759bc
    clientSecret: b46c6894e64e3e086debead5c9757d98dfbf765b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
